### ISSUE TITLE
build QEMU in an antlir container

### ISSUE THREAD

**Issue by vmagro** [facebookincubator/antlir#119]
* Build QEMU in an Antlir container (like we do for systemd internally) so that we can use more modern versions and be consistent across internal + oss usage
* This should be done first to have a baseline level of VM support in opensource for GitHub Actions and common ground across users

**Comment by vmagro** [comment]
See https://github.com/facebookincubator/antlir/blob/main/third-party/fedora33/qemu/BUCK for where we use the QEMU installed on the host as a temporary hack

To build QEMU from source, it would be nice to use an `http_file` rule to download the source tarball (https://www.qemu.org/download/#source) and then an `image.genrule_layer` (https://facebookincubator.github.io/antlir/docs/genrule-layer) to actually build the binary, efi bios and any other files we expect for a qemu installation

**Comment by baioc** [comment]
@vmagro I believe this issue can be closed after #136
