### ISSUE TITLE
Fix genrule_layer example

### ISSUE THREAD

**Issue by baioc** [facebookincubator/antlir#133]
The [documentation on `image.genrule_layer`](https://facebookincubator.github.io/antlir/docs/genrule-layer/) provides the following example:

```python
image.layer(
    name = '_setup_foo',
    parent_layer = '...',
    features = [
        # `genrule_layer` runs as `nobody` by default
        image.ensure_subdirs_exist('/', 'output', user='nobody'),
        image.install(':foo', '/output/_temp_foo'),
    ],
)

image.genrule_layer(
    name = '_translate_foo',
    parent_layer = ':setup',
    cmd = ['/bin/sh', '-c', 'tr a-z A-Z < /output/_temp_foo > /output/FOO'],
)

image.layer(
    name = 'foo',
    parent_layer = ':_translate_foo',
    # Clean up temporary state
    features = [image.remove_path('/output/_temp_foo')],
)
```

However, this is broken in more than one way:
- The `genrule_layer` rule is missing two required arguments: `rule_type` and `antlir_rule`
- `remove_path` should be just `remove`
- The parent layer used by genrule should be `:_setup_foo` instead of `:setup`
- As it is currently written, there is a circular dependency on the target `:foo`, since it is installed in `_setup_foo`. I assume this would be some file in the host system that is installed in the image and used as the input to the genrule_layer.

Let me know if I got something wrong. Will be creating a PR to fix this soon.

**Comment by snarkmaster** [comment]
Thanks for the careful proofreading! I think you want these values for the kwargs:

```
rule_type = "decsribe_what_your_rule_does"
antlir_rule = "user-facing",  # The semantics of this don't make much sense in OSS, yet
```

You're right about `remove` & `parent_layer = ":_setup_foo"`.

I have a small correction for `image.install()`.

This should actually be something like this:

```
export_file(name = "untranslated-foo")  # or a real build rule

image.install(":untranslated-foo", "/output/_temp_foo"),
```

So the intent of `install()` is to put a Buck build artifact into the image. See also `install_buck_runnable`.

I look forward to the PR!

**Comment by baioc** [comment]
I believe PR #134 resolves this now.
