### ISSUE TITLE
Update documentation's installation section

### ISSUE THREAD

**Issue by SaurabhAgarwala** [facebookincubator/antlir#137]
The installation section of the documentation is missing few important details which will help a new contributor to get started quickly with the setup. These include:

- Having `rpm2cpio`, `zstd` as dependencies
- Not running `buck` as root user
-  As image builds themselves run through `sudo`, this requires adding the user to the sudoers file, so that password is not required on every invocation, else the build will fail.

I am interested to work on adding these details to the documentation.

**Comment by vmagro** [comment]
Sounds great, you two are the first to try to set this up from scratch who don't actually work on this project at FB, so thanks for surfacing the problems :)
